apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: multi-cluster-app
  namespace: multi-cluster-app
spec:
  type: Git
  pathname: 'https://github.com/nmasse-itix/multi-cluster-app.git'
